/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.cirurgica.view.produto;

import br.com.cirurgica.controller.ProdutoController;
import br.com.cirurgica.model.FornecedorProduto;
import br.com.cirurgica.model.Produto;
import br.com.cirurgica.view.IView;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.WindowListener;
import java.util.ArrayList;
import java.util.EventListener;
import java.util.List;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author Leo
 */
public final class GestaoProduto extends javax.swing.JFrame implements IView {

    /**
     * Creates new form GestaoProduto
     */
    /**
     * Este atributo são os valores dos campos da tela.
     */
    private Produto produto;


    /**
     * Deve executar somente a inicialização nativa e dos listeners
     * @param listener
     */
    public GestaoProduto(EventListener listener) {
        initComponents();
        atribuirListeners(listener);
    }

    public List<Produto> getListaProduto(){
        return this.listaProduto;
    }

    public Produto getProduto(){
        return this.produto;
    }
    /**
     * Executa procedimentos para popular a tabela
     */

    @Override
    public void atribuirListeners(EventListener listener) {
        ActionListener action = (ActionListener) listener;
        KeyListener key = (KeyListener) listener;
        WindowListener window = (WindowListener) listener;

        btnAdicionar.addActionListener(action);
        btnAdicionar.addKeyListener(key);

        btnAlterarProduto.addActionListener(action);
        btnAlterarProduto.addKeyListener(key);

        btnVoltar.addActionListener(action);
        btnVoltar.addKeyListener(key);

        btnExcluirProduto.addActionListener(action);
        btnExcluirProduto.addKeyListener(key);

        btnPesquisar.addActionListener(action);
        btnPesquisar.addKeyListener(key);
        txtNome.addKeyListener(key);

        btnMarkup.addActionListener(action);
        btnMarkup.addKeyListener(key);
        this.addWindowListener(window);
    }

    public String getNomePesquisa(){
        return txtNome.getText().trim();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        listaProduto = org.jdesktop.observablecollections.ObservableCollections.observableList(new ArrayList());
        moneyCellRenderer = new br.com.cirurgica.view.utils.cell.MoneyCellRenderer();
        panelCampos = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        scrollTableGestao = new javax.swing.JScrollPane();
        tbGestaoProdutos = new javax.swing.JTable();
        tbGestaoProdutos.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
            @Override
            public void valueChanged(ListSelectionEvent arg0) {
                if(tbGestaoProdutos.getSelectedRow() != -1){
                    produto = listaProduto.get(tbGestaoProdutos.getSelectedRow());
                    btnExcluirProduto.setEnabled(true);
                    btnAlterarProduto.setEnabled(true);
                }else{
                    produto = null;
                    btnExcluirProduto.setEnabled(false);
                    btnAlterarProduto.setEnabled(false);        
                }
            }
        });
        panelBotoes = new javax.swing.JPanel();
        btnAdicionar = new javax.swing.JButton();
        lblAdicionar = new javax.swing.JLabel();
        btnPesquisar = new javax.swing.JButton();
        lblPesquisar = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        lblVoltar = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        btnAlterarProduto = new javax.swing.JButton();
        lblAlterar = new javax.swing.JLabel();
        btnExcluirProduto = new javax.swing.JButton();
        lblExcluir = new javax.swing.JLabel();
        btnMarkup = new javax.swing.JButton();

        moneyCellRenderer.setText("moneyCellRenderer1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Ana Maria Cirurgica - Produtos");
        setBounds(new java.awt.Rectangle(400, 200, 0, 0));
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        panelCampos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        lblTitulo.setText("Gestão de Produtos");
        panelCampos.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, -1, -1));

        tbGestaoProdutos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tbGestaoProdutos.setFocusable(false);
        tbGestaoProdutos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, listaProduto, tbGestaoProdutos);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${cdFarmaceutico}"));
        columnBinding.setColumnName("Código");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${nome}"));
        columnBinding.setColumnName("Nome");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${fornecedorCollection}"));
        columnBinding.setColumnName("Fornecedores");
        columnBinding.setColumnClass(java.util.List.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${qtdeEstoque}"));
        columnBinding.setColumnName("Estoque");
        columnBinding.setColumnClass(Integer.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${valorVenda}"));
        columnBinding.setColumnName("Preço Varejo");
        columnBinding.setColumnClass(Float.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${valorVendaAtacado}"));
        columnBinding.setColumnName("Preço Atacado");
        columnBinding.setColumnClass(Float.class);
        columnBinding.setEditable(false);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        scrollTableGestao.setViewportView(tbGestaoProdutos);
        tbGestaoProdutos.getColumnModel().getColumn(0).setPreferredWidth(50);
        tbGestaoProdutos.getColumnModel().getColumn(1).setMinWidth(200);
        tbGestaoProdutos.getColumnModel().getColumn(1).setPreferredWidth(300);
        tbGestaoProdutos.getColumnModel().getColumn(2).setMinWidth(200);
        tbGestaoProdutos.getColumnModel().getColumn(2).setPreferredWidth(250);
        tbGestaoProdutos.getColumnModel().getColumn(3).setResizable(false);
        tbGestaoProdutos.getColumnModel().getColumn(3).setPreferredWidth(50);
        tbGestaoProdutos.getColumnModel().getColumn(4).setResizable(false);
        tbGestaoProdutos.getColumnModel().getColumn(4).setPreferredWidth(90);
        tbGestaoProdutos.getColumnModel().getColumn(4).setCellRenderer(moneyCellRenderer);
        tbGestaoProdutos.getColumnModel().getColumn(5).setResizable(false);
        tbGestaoProdutos.getColumnModel().getColumn(5).setPreferredWidth(90);
        tbGestaoProdutos.getColumnModel().getColumn(5).setCellRenderer(moneyCellRenderer);

        panelCampos.add(scrollTableGestao, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 860, 400));

        panelBotoes.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnAdicionar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/bt_novo_cliente.png"))); // NOI18N
        btnAdicionar.setActionCommand("GestaoProduto.adicionarProduto");
        btnAdicionar.setName("GestaoProduto.adicionarProduto"); // NOI18N
        btnAdicionar.setPreferredSize(new java.awt.Dimension(90, 60));

        lblAdicionar.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblAdicionar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAdicionar.setText("ADICIONAR");

        btnPesquisar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/bt_pesquisar.png"))); // NOI18N
        btnPesquisar.setActionCommand("GestaoProduto.pesquisarProduto");
        btnPesquisar.setName("GestaoProduto.pesquisarProduto"); // NOI18N
        btnPesquisar.setPreferredSize(new java.awt.Dimension(90, 60));
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        lblPesquisar.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblPesquisar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPesquisar.setText("PESQUISAR");

        btnVoltar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/bt_voltar.png"))); // NOI18N
        btnVoltar.setActionCommand("GestaoProduto.voltar");
        btnVoltar.setName("GestaoProduto.voltar"); // NOI18N
        btnVoltar.setPreferredSize(new java.awt.Dimension(90, 60));

        lblVoltar.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblVoltar.setText("VOLTAR(ESC)");

        txtNome.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        txtNome.setToolTipText("Digite um nome para a pesquisa");
        txtNome.setName("GestaoProduto.txtNome"); // NOI18N

        lblNome.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblNome.setText("Nome:");

        btnAlterarProduto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAlterarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/bt_alterar.png"))); // NOI18N
        btnAlterarProduto.setActionCommand("GestaoProduto.alterarProduto");
        btnAlterarProduto.setEnabled(false);
        btnAlterarProduto.setName("GestaoProduto.alterarProduto"); // NOI18N
        btnAlterarProduto.setPreferredSize(new java.awt.Dimension(90, 60));

        lblAlterar.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblAlterar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAlterar.setText("ALTERAR");

        btnExcluirProduto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnExcluirProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/bt_excluir.png"))); // NOI18N
        btnExcluirProduto.setActionCommand("GestaoProduto.excluirProduto");
        btnExcluirProduto.setEnabled(false);
        btnExcluirProduto.setName("GestaoProduto.excluirProduto"); // NOI18N
        btnExcluirProduto.setPreferredSize(new java.awt.Dimension(90, 60));

        lblExcluir.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblExcluir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblExcluir.setText("EXCLUIR");

        btnMarkup.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnMarkup.setText("Alterar Markup");
        btnMarkup.setActionCommand("GestaoProduto.alterarMarkup");
        btnMarkup.setName("GestaoProduto.alterarMarkup"); // NOI18N

        org.jdesktop.layout.GroupLayout panelBotoesLayout = new org.jdesktop.layout.GroupLayout(panelBotoes);
        panelBotoes.setLayout(panelBotoesLayout);
        panelBotoesLayout.setHorizontalGroup(
            panelBotoesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelBotoesLayout.createSequentialGroup()
                .add(panelBotoesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(panelBotoesLayout.createSequentialGroup()
                        .add(12, 12, 12)
                        .add(btnAdicionar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 59, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(panelBotoesLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(lblAdicionar)))
                .add(18, 18, 18)
                .add(panelBotoesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(lblAlterar, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(btnAlterarProduto, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 59, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(panelBotoesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(btnExcluirProduto, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 59, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(lblExcluir, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 59, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(panelBotoesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(panelBotoesLayout.createSequentialGroup()
                        .add(btnPesquisar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 59, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(panelBotoesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(lblNome)
                            .add(txtNome, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 146, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(panelBotoesLayout.createSequentialGroup()
                        .add(lblPesquisar)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(btnMarkup, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(panelBotoesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(lblVoltar)
                    .add(btnVoltar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 64, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        panelBotoesLayout.setVerticalGroup(
            panelBotoesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .add(panelBotoesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(panelBotoesLayout.createSequentialGroup()
                        .add(panelBotoesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(btnVoltar, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(btnAlterarProduto, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(btnAdicionar, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(btnExcluirProduto, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(btnPesquisar, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .add(panelBotoesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(panelBotoesLayout.createSequentialGroup()
                                .add(7, 7, 7)
                                .add(panelBotoesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(lblAdicionar)
                                    .add(lblAlterar)
                                    .add(lblExcluir)
                                    .add(lblPesquisar)))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, panelBotoesLayout.createSequentialGroup()
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(lblVoltar))))
                    .add(panelBotoesLayout.createSequentialGroup()
                        .add(11, 11, 11)
                        .add(lblNome)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(txtNome, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(btnMarkup)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelCampos.add(panelBotoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 460, 580, -1));

        getContentPane().add(panelCampos);

        bindingGroup.bind();

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-913)/2, (screenSize.height-630)/2, 913, 630);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestaoProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestaoProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestaoProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestaoProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProdutoController().init();
            }
        });
    }

    @Override
    public void cancelarFechamento() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public void fecharJanela() {
        this.dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnAlterarProduto;
    private javax.swing.JButton btnExcluirProduto;
    private javax.swing.JButton btnMarkup;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel lblAdicionar;
    private javax.swing.JLabel lblAlterar;
    private javax.swing.JLabel lblExcluir;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblPesquisar;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblVoltar;
    private java.util.List<br.com.cirurgica.model.Produto> listaProduto;
    private br.com.cirurgica.view.utils.cell.MoneyCellRenderer moneyCellRenderer;
    private javax.swing.JPanel panelBotoes;
    private javax.swing.JPanel panelCampos;
    private javax.swing.JScrollPane scrollTableGestao;
    private javax.swing.JTable tbGestaoProdutos;
    private javax.swing.JTextField txtNome;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}

class PressKey implements KeyListener{

    @Override
    public void keyTyped(KeyEvent e) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public void keyPressed(KeyEvent e) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public void keyReleased(KeyEvent e) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

}
