/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.cirurgica.view.utils;

import javax.swing.JProgressBar;

/**
 *
 * @author dfelix3
 */
public class ProgressBarView extends javax.swing.JFrame {
    /**
     * Creates new form ProgressBarView
     */
    public ProgressBarView(String info) {
        initComponents();       
        this.labelInformacao.setText(info);
    }
    public static void main(String args[]){
        ProgressBarView rel = new ProgressBarView("Teste de progressos");
        rel.setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelData = new javax.swing.JPanel();
        progressBar = new javax.swing.JProgressBar();
        labelInformacao = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        panelData.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        panelData.setLayout(null);

        progressBar.setIndeterminate(true);
        progressBar.setPreferredSize(new java.awt.Dimension(500, 20));
        panelData.add(progressBar);
        progressBar.setBounds(40, 10, 270, 14);

        labelInformacao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelInformacao.setLabelFor(progressBar);
        labelInformacao.setText("Carregando Relatório...");
        labelInformacao.setToolTipText("Aguarde...");
        panelData.add(labelInformacao);
        labelInformacao.setBounds(95, 30, 140, 14);

        getContentPane().add(panelData);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-342)/2, (screenSize.height-49)/2, 342, 49);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelInformacao;
    private javax.swing.JPanel panelData;
    private javax.swing.JProgressBar progressBar;
    // End of variables declaration//GEN-END:variables
}
