/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.cirurgica.view.despesa;

import br.com.cirurgica.dao.CirurgicaConnectionManager;
import br.com.cirurgica.view.PrincipalView;
import br.com.cirurgica.view.pedido.CadastrarPedido;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author 13b Pessoal
 */
public class CadastrarDespesa extends javax.swing.JFrame {

    Map<String, Integer> mapaTipoDespesa;

    /**
     * Creates new form CadastrarDespesa
     */
    public CadastrarDespesa() {
        initComponents();

        btnAdicionar.addKeyListener(new PressEnter());
        btnCancelar.addKeyListener(new PressEnter());
        btnLimpar.addKeyListener(new PressEnter());
        txtValorDespesa.addKeyListener(new PressEnter());
        ckDespegaPaga.addKeyListener(new PressEnter());
        cbDataVencimento.addKeyListener(new PressEnter());
        cbDataReferente.addKeyListener(new PressEnter());
        cbTipoDespesa.addKeyListener(new PressEnter());

        popularComboTipoDespesa();
         setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        this.setResizable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnAdicionar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txtValorDespesa = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        ckDespegaPaga = new javax.swing.JCheckBox();
        cbDataVencimento = new org.freixas.jcalendar.JCalendarCombo();
        cbTipoDespesa = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        cbDataReferente = new org.freixas.jcalendar.JCalendarCombo();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescricao = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ana Maria Cirurgica - Cadastrar Despesa");
        setBounds(new java.awt.Rectangle(300, 40, 0, 0));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        jLabel9.setText("Cadastro de Despesa");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel2.setText("Data de Vencimento:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel4.setText("Tipo de Despesa:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, -1, -1));

        btnAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/bt_novo_cliente.png"))); // NOI18N
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, 100, 70));

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/bt_voltar.png"))); // NOI18N
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 410, 100, 70));

        btnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/bt_clear.png"))); // NOI18N
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 410, 100, 70));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel13.setText("R$");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 37, -1, -1));

        txtValorDespesa.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        txtValorDespesa.setPreferredSize(new java.awt.Dimension(6, 24));
        txtValorDespesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorDespesaActionPerformed(evt);
            }
        });
        jPanel2.add(txtValorDespesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 33, 80, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel7.setText("Valor da Despesa:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 13, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel14.setText("Ex. : 45,99");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 63, -1, -1));

        ckDespegaPaga.setBackground(new java.awt.Color(204, 204, 255));
        ckDespegaPaga.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        ckDespegaPaga.setText("Despesa Paga");
        jPanel2.add(ckDespegaPaga, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 300, 100));
        jPanel1.add(cbDataVencimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 79, -1, -1));

        cbTipoDespesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoDespesaActionPerformed(evt);
            }
        });
        jPanel1.add(cbTipoDespesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 300, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel5.setText("Data de Pagamento:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, -1, -1));
        jPanel1.add(cbDataReferente, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LIMPAR CAMPOS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 480, 100, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel3.setText("ADICIONAR DESPESA");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 480, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel8.setText("CANCELAR CADASTRO");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 480, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel6.setText("Descrição:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, -1, -1));

        txtDescricao.setColumns(20);
        txtDescricao.setRows(5);
        jScrollPane1.setViewportView(txtDescricao);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 300, -1));

        getContentPane().add(jPanel1);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-583)/2, (screenSize.height-550)/2, 583, 550);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed

        cadastrarDespesa();
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        try {
            voltar();
        } catch (ParseException ex) {
            Logger.getLogger(CadastrarDespesa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        limparCampos();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void txtValorDespesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorDespesaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorDespesaActionPerformed

    private void cbTipoDespesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoDespesaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTipoDespesaActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            voltar();
        } catch (ParseException ex) {
            Logger.getLogger(CadastrarDespesa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowClosing

    public void cadastrarDespesa() {

        if (txtDescricao.getText().equals("") || txtValorDespesa.getText().equals("") || cbDataVencimento.getSelectedItem().equals(null) || cbDataReferente.getSelectedItem().equals(null)
                || cbTipoDespesa.getSelectedItem().equals(null)){

           JOptionPane.showMessageDialog(this, "Preencha todos os campos antes de Cadastrar uma Despesa!");

        }else{

        String sql = "insert into despesa(valor_despesa, data_vencimento, isPaga, cd_tipo_despesa, data_referente,descricao) "
                + "values(?,?,?,?,?,?);";


        Connection con = CirurgicaConnectionManager.getConnection();
        PreparedStatement stm;


        try {

            stm = con.prepareStatement(sql);
            String dataVencimento = new SimpleDateFormat("yyyy-MM-dd").format(cbDataVencimento.getDate());
            String dataReferente = new SimpleDateFormat("yyyy-MM-dd").format(cbDataReferente.getDate());

            stm.setString(1, txtValorDespesa.getText().replace(",", "."));
            stm.setString(2, dataVencimento);
            stm.setString(3, (ckDespegaPaga.isSelected() ? "1" : "0"));
            stm.setString(4, mapaTipoDespesa.get(cbTipoDespesa.getSelectedItem().toString()).toString());
            stm.setString(5, dataReferente);
            stm.setString(6, txtDescricao.getText());
            stm.executeUpdate();

            stm.close();
            con.close();

            JOptionPane.showMessageDialog(this, "CADASTRO EFETUADO COM SUCESSO!!!", "Cadastro", JOptionPane.INFORMATION_MESSAGE);



            this.setVisible(false);
            GestaoDespesa gd = new GestaoDespesa();
            gd.setVisible(true);


        } catch (Exception e) {

            e.printStackTrace();
        }
        }
    }

    public void voltar() throws ParseException {

        if (JOptionPane.showConfirmDialog(this, "Tem certeza que deseja cancelar o cadastro? (Pressione ESC para Cancelar)", "Confirmação", 2, 3) == 0) {


            GestaoDespesa gd = new GestaoDespesa();
            gd.setVisible(true);
            this.dispose();


        }
    }

    public void popularComboTipoDespesa() {
        String sql = "select * from tipodespesa";
        Connection con;
        con = CirurgicaConnectionManager.getConnection();


        mapaTipoDespesa = new HashMap<>();

        try {
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            while (rs.next()) {

                mapaTipoDespesa.put(rs.getString("nm_tipo_despesa"), rs.getInt("cd_tipo_despesa"));
                cbTipoDespesa.addItem(rs.getString("nm_tipo_despesa"));
            }

            stmt.close();

        } catch (SQLException ex) {
            Logger.getLogger(PrincipalView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarDespesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarDespesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarDespesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarDespesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarDespesa().setVisible(true);
            }
        });
    }

    public void limparCampos() {
        cbDataVencimento.setDate(new Date());
        cbDataReferente.setDate(new Date());
        txtValorDespesa.setText(null);
        ckDespegaPaga.setSelected(false);
        cbTipoDespesa.setSelectedIndex(0);

    }

    class PressEnter implements KeyListener {

        public void keyPressed(KeyEvent e) {
            // TODO Auto-generated method stub

            if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                if (btnAdicionar.isFocusOwner()) {

                    cadastrarDespesa();

                } else if (btnCancelar.isFocusOwner()) {
                    try {
                        voltar();
                    } catch (ParseException ex) {
                        Logger.getLogger(CadastrarPedido.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } else if (btnLimpar.isFocusOwner()) {
                    limparCampos();
                } else if (ckDespegaPaga.isFocusOwner()) {
                    if (ckDespegaPaga.isSelected() == true) {
                        ckDespegaPaga.setSelected(false);
                    } else {
                        ckDespegaPaga.setSelected(true);
                    }
                }
            } else if (e.getKeyCode() == KeyEvent.VK_ESCAPE) {
                try {
                    voltar();
                } catch (ParseException ex) {
                    Logger.getLogger(CadastrarPedido.class.getName()).log(Level.SEVERE, null, ex);
                }
            }


        }

        public void keyReleased(KeyEvent e) {
        }

        public void keyTyped(KeyEvent e) {
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnLimpar;
    private org.freixas.jcalendar.JCalendarCombo cbDataReferente;
    private org.freixas.jcalendar.JCalendarCombo cbDataVencimento;
    private javax.swing.JComboBox cbTipoDespesa;
    private javax.swing.JCheckBox ckDespegaPaga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtDescricao;
    private javax.swing.JTextField txtValorDespesa;
    // End of variables declaration//GEN-END:variables
}
