/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.cirurgica.view;

import br.com.cirurgica.dao.LoginDAO;
import br.com.cirurgica.model.Login;
import com.utilidades.Utilidades;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.math.BigInteger;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.NoResultException;
import javax.swing.JOptionPane;

/**
 *
 * @author 13b Pessoal
 */
public class LoginView extends javax.swing.JFrame {

    /**
     * Creates new form LoginView
     */
    String nomeUsuario = "";

    public LoginView() {
        initComponents();

        btnEntrar.addKeyListener(new PressEnter());
        txtUsuario.addKeyListener(new PressEnter());
        txtSenha.addKeyListener(new PressEnter());
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/resources/icon-principal.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        loginTela = new br.com.cirurgica.model.Login();
        panelTela = new javax.swing.JPanel();
        btnSair = new javax.swing.JButton();
        btnEntrar = new javax.swing.JButton();
        panelDados = new javax.swing.JPanel();
        lblUsuario = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtSenha = new javax.swing.JPasswordField();
        lblTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ana Maria Cirurgica - Login");
        setBackground(new java.awt.Color(102, 204, 0));
        setBounds(new java.awt.Rectangle(400, 200, 0, 0));
        setForeground(new java.awt.Color(255, 153, 153));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        panelTela.setLayout(new java.awt.GridBagLayout());

        btnSair.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/cancel.png"))); // NOI18N
        btnSair.setText("SAIR");
        btnSair.setActionCommand("Login.sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 5, 25, 70);
        panelTela.add(btnSair, gridBagConstraints);

        btnEntrar.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnEntrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ok.png"))); // NOI18N
        btnEntrar.setText("ENTRAR");
        btnEntrar.setActionCommand("Login.entrar");
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 70, 25, 0);
        panelTela.add(btnEntrar, gridBagConstraints);

        panelDados.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelDados.setLayout(new java.awt.GridBagLayout());

        lblUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUsuario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblUsuario.setText("Usuário:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 5, 2);
        panelDados.add(lblUsuario, gridBagConstraints);

        lblSenha.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSenha.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSenha.setText("Senha:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 20, 20, 2);
        panelDados.add(lblSenha, gridBagConstraints);

        txtUsuario.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, loginTela, org.jdesktop.beansbinding.ELProperty.create("${nmLogin}"), txtUsuario, org.jdesktop.beansbinding.BeanProperty.create("text_ON_ACTION_OR_FOCUS_LOST"), "usuarioLoginBinding");
        bindingGroup.addBinding(binding);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(20, 2, 5, 20);
        panelDados.add(txtUsuario, gridBagConstraints);

        txtSenha.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 2, 20, 20);
        panelDados.add(txtSenha, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        panelTela.add(panelDados, gridBagConstraints);

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Login");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 10);
        panelTela.add(lblTitulo, gridBagConstraints);

        getContentPane().add(panelTela);

        bindingGroup.bind();

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-426)/2, (screenSize.height-304)/2, 426, 304);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        try {
            realizarLogin();
        } catch (Exception ex) {
            Logger.getLogger(LoginView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnEntrarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void realizarLogin() throws ParseException {
        if (login()) {
            JOptionPane.showMessageDialog(this, "Olá " + nomeUsuario, "Bem vindo!", JOptionPane.INFORMATION_MESSAGE);
            final Thread tFormPrincipal = new Thread() {
                @Override
                public void run() {
                    PrincipalView p = new PrincipalView();
                    p.setUsuarioLogado(Utilidades.retornaNomeLogado());
                    p.setVisible(true);
                }
            };

            tFormPrincipal.start();
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Usuário e/ou senha incorreto(s)");
            txtSenha.setText("");
            txtSenha.requestFocus();
        }
    }

    private String gerarHash(String senha) {
        try {
            MessageDigest md;
            md = MessageDigest.getInstance("MD5");
            BigInteger hash = new BigInteger(1, md.digest(senha.getBytes()));
            String senhaHash = hash.toString(16);

            return senhaHash;
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(LoginView.class.getName()).log(Level.SEVERE, null, ex);
            return "";
        }
    }

    private boolean login() {
        LoginDAO dao = new LoginDAO();
        String hash = gerarHash(new String(txtSenha.getPassword()));
        loginTela.setNmSenha(hash);
        Login result = null;
        try {
            result = dao.getUser(loginTela);
        } catch (NoResultException e) {
            return false;
        }
        nomeUsuario = result.getCdUsuario().getCdPessoa().getNmPessoa();
        Utilidades.pessoaLogada = result.getCdUsuario().getCdPessoa();
        Utilidades.usuarioLogado = result.getCdUsuario();
        return true;
    }

    class PressEnter implements KeyListener {

        public void keyPressed(KeyEvent e) {
            // TODO Auto-generated method stub

            if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                try {
                    realizarLogin();
                } catch (ParseException ex) {
                    Logger.getLogger(LoginView.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else if (e.getKeyCode() == KeyEvent.VK_ESCAPE) {
                System.exit(0);
            }
        }

        public void keyReleased(KeyEvent e) {
            // JOptionPane.showMessageDialog(null, "2: " + KeyEvent.getKeyText(e.getKeyCode()));
            // TODO Auto-generated method stub
        }

        public void keyTyped(KeyEvent e) {
            // TODO Auto-generated method stub
            // JOptionPane.showMessageDialog(null, "3: " + KeyEvent.getKeyText(e.getKeyCode()));
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUsuario;
    private br.com.cirurgica.model.Login loginTela;
    private javax.swing.JPanel panelDados;
    private javax.swing.JPanel panelTela;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JTextField txtUsuario;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
