    /*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.cirurgica.view;

import br.com.cirurgica.controller.ProdutoController;
import br.com.cirurgica.view.cliente.GestaoCliente;
import br.com.cirurgica.view.despesa.GestaoDespesa;
import br.com.cirurgica.view.fornecedor.GestaoFornecedor;
import br.com.cirurgica.view.grafico.GestaoGrafico;
import br.com.cirurgica.view.notafiscal.GestaoNotaFiscal;
import br.com.cirurgica.view.pedido.GestaoPedido;
import br.com.cirurgica.view.relatorio.EmitirRelatorioEstoque;
import br.com.cirurgica.view.relatorio.EmitirRelatorioVendas;
import br.com.cirurgica.view.relatorio.GestaoRelatorio;
import br.com.cirurgica.view.usuario.GestaoUsuario;
import br.com.cirurgica.view.venda.GestaoVenda;
import br.com.cirurgica.view.venda.PesquisarCliente;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author 13b Pessoal
 */
public class PrincipalView extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalView
     */
    public PrincipalView() {
        initComponents();

        btnCLientes.addKeyListener(new PressEnter());
        btnProdutos.addKeyListener(new PressEnter());
        btnUsuarios.addKeyListener(new PressEnter());
        btnRelatorios.addKeyListener(new PressEnter());
        btnFornecedor.addKeyListener(new PressEnter());
        btnGraficos.addKeyListener(new PressEnter());
        btnContas.addKeyListener(new PressEnter());
        btnVendas.addKeyListener(new PressEnter());
        btnNovaVenda.addKeyListener(new PressEnter());
        btnNotas.addKeyListener(new PressEnter());

        this.setIconImage(Toolkit.getDefaultToolkit().getImage(PrincipalView.class.getResource("/resources/icon-principal.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelDados = new javax.swing.JPanel();
        panelBotoes = new javax.swing.JPanel();
        btnCLientes = new javax.swing.JButton();
        btnProdutos = new javax.swing.JButton();
        lblClientes = new javax.swing.JLabel();
        lblProdutos = new javax.swing.JLabel();
        btnUsuarios = new javax.swing.JButton();
        lblUsuarios = new javax.swing.JLabel();
        lblFornecedor = new javax.swing.JLabel();
        btnVendas = new javax.swing.JButton();
        lblVendas = new javax.swing.JLabel();
        btnFornecedor = new javax.swing.JButton();
        btnPedido = new javax.swing.JButton();
        lblCompras = new javax.swing.JLabel();
        lblInfo = new javax.swing.JLabel();
        panelBotoesRelatorios = new javax.swing.JPanel();
        btnGraficos = new javax.swing.JButton();
        lblGraficos = new javax.swing.JLabel();
        btnContas = new javax.swing.JButton();
        lblContas = new javax.swing.JLabel();
        lblRelatorios = new javax.swing.JLabel();
        btnRelatorios = new javax.swing.JButton();
        btnNotas = new javax.swing.JButton();
        lblNotas = new javax.swing.JLabel();
        btnNovaVenda = new javax.swing.JButton();
        lblNovaVenda = new javax.swing.JLabel();
        lblUsuarioLogado = new javax.swing.JLabel();
        lvlLogo = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        mnuArquivo = new javax.swing.JMenu();
        mnuItemNovaVenda = new javax.swing.JMenuItem();
        mnuItemSair = new javax.swing.JMenuItem();
        mnuCadastros = new javax.swing.JMenu();
        mnuItemClientes = new javax.swing.JMenuItem();
        mnuItemProdutos = new javax.swing.JMenuItem();
        mnuItemFornecedores = new javax.swing.JMenuItem();
        mnuItemPedidos = new javax.swing.JMenuItem();
        mnuRelatorios = new javax.swing.JMenu();
        mnuItemRelFluxoCaixa = new javax.swing.JMenuItem();
        mnuItemRelDespesas = new javax.swing.JMenuItem();
        mnuAdmin = new javax.swing.JMenu();
        mnuItemUsuarios = new javax.swing.JMenuItem();
        mnuItemGraficos = new javax.swing.JMenuItem();
        mnuItemDespesas = new javax.swing.JMenuItem();
        mnuItemCaixa = new javax.swing.JMenuItem();
        mnuItemVendas = new javax.swing.JMenuItem();
        mnuItemNotas = new javax.swing.JMenuItem();
        mnuAjuda = new javax.swing.JMenu();
        mnuItemSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Ana Maria Cirurgica - Principal");
        setBounds(new java.awt.Rectangle(100, 50, 0, 0));
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/resources/icon-principal.png")));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        panelDados.setMaximumSize(new java.awt.Dimension(1080, 720));
        panelDados.setLayout(new java.awt.GridBagLayout());

        panelBotoes.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelBotoes.setLayout(new java.awt.GridBagLayout());

        btnCLientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/bt_clientes.png"))); // NOI18N
        btnCLientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCLientesActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = -25;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 5, 10);
        panelBotoes.add(btnCLientes, gridBagConstraints);

        btnProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/bt_produtos.png"))); // NOI18N
        btnProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdutosActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = -25;
        gridBagConstraints.insets = new java.awt.Insets(20, 15, 5, 15);
        panelBotoes.add(btnProdutos, gridBagConstraints);

        lblClientes.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblClientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClientes.setText("CLIENTES");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 20, 5, 10);
        panelBotoes.add(lblClientes, gridBagConstraints);

        lblProdutos.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblProdutos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProdutos.setText("PRODUTOS");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 5, 15);
        panelBotoes.add(lblProdutos, gridBagConstraints);

        btnUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/bt_usuarios.png"))); // NOI18N
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = -25;
        gridBagConstraints.insets = new java.awt.Insets(20, 10, 5, 20);
        panelBotoes.add(btnUsuarios, gridBagConstraints);

        lblUsuarios.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblUsuarios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsuarios.setText("USUÁRIOS");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 20);
        panelBotoes.add(lblUsuarios, gridBagConstraints);

        lblFornecedor.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblFornecedor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFornecedor.setText("FORNECEDOR");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 20, 20);
        panelBotoes.add(lblFornecedor, gridBagConstraints);

        btnVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/bt_venda.png"))); // NOI18N
        btnVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVendasActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = -25;
        gridBagConstraints.insets = new java.awt.Insets(5, 20, 5, 10);
        panelBotoes.add(btnVendas, gridBagConstraints);

        lblVendas.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblVendas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVendas.setText("VENDAS");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(5, 20, 20, 10);
        panelBotoes.add(lblVendas, gridBagConstraints);

        btnFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/bt_fornecedor.png"))); // NOI18N
        btnFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFornecedorActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = -25;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 20);
        panelBotoes.add(btnFornecedor, gridBagConstraints);

        btnPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/bt_pedido.png"))); // NOI18N
        btnPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPedidoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = -25;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 5, 15);
        panelBotoes.add(btnPedido, gridBagConstraints);

        lblCompras.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblCompras.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCompras.setText("COMPRAS");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 20, 15);
        panelBotoes.add(lblCompras, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(45, 30, 0, 0);
        panelDados.add(panelBotoes, gridBagConstraints);

        lblInfo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblInfo.setText("Produtos Cirurgicos e Acessórios");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 23, 0, 0);
        panelDados.add(lblInfo, gridBagConstraints);

        panelBotoesRelatorios.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelBotoesRelatorios.setLayout(new java.awt.GridBagLayout());

        btnGraficos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/bt_grafico.png"))); // NOI18N
        btnGraficos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraficosActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = -25;
        gridBagConstraints.insets = new java.awt.Insets(20, 15, 5, 15);
        panelBotoesRelatorios.add(btnGraficos, gridBagConstraints);

        lblGraficos.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblGraficos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGraficos.setText("GRÁFICOS");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 5, 15);
        panelBotoesRelatorios.add(lblGraficos, gridBagConstraints);

        btnContas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/bt_despesa.png"))); // NOI18N
        btnContas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContasActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = -25;
        gridBagConstraints.insets = new java.awt.Insets(20, 10, 5, 20);
        panelBotoesRelatorios.add(btnContas, gridBagConstraints);

        lblContas.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblContas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblContas.setText("CONTAS");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 20);
        panelBotoesRelatorios.add(lblContas, gridBagConstraints);

        lblRelatorios.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblRelatorios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRelatorios.setText("RELATORIOS");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 20, 5, 10);
        panelBotoesRelatorios.add(lblRelatorios, gridBagConstraints);

        btnRelatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/bt_relatorios.png"))); // NOI18N
        btnRelatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatoriosActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = -25;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 5, 10);
        panelBotoesRelatorios.add(btnRelatorios, gridBagConstraints);

        btnNotas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/bt_nota_fiscal.png"))); // NOI18N
        btnNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNotasActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = -25;
        gridBagConstraints.insets = new java.awt.Insets(5, 20, 5, 10);
        panelBotoesRelatorios.add(btnNotas, gridBagConstraints);

        lblNotas.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblNotas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNotas.setText("NOTAS");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(5, 20, 5, 10);
        panelBotoesRelatorios.add(lblNotas, gridBagConstraints);

        btnNovaVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/bt_nova_venda.png"))); // NOI18N
        btnNovaVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovaVendaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = -25;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 5, 15);
        panelBotoesRelatorios.add(btnNovaVenda, gridBagConstraints);

        lblNovaVenda.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblNovaVenda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNovaVenda.setText("NOVA VENDA");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 5, 15);
        panelBotoesRelatorios.add(lblNovaVenda, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 41;
        gridBagConstraints.ipady = 65;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(45, 14, 0, 0);
        panelDados.add(panelBotoesRelatorios, gridBagConstraints);

        lblUsuarioLogado.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblUsuarioLogado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblUsuarioLogado.setText("Usuário Logado: Administrador");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.ipadx = 844;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(50, 30, 66, 25);
        panelDados.add(lblUsuarioLogado, gridBagConstraints);

        lvlLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lvlLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Logo.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = -180;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(80, 355, 0, 0);
        panelDados.add(lvlLogo, gridBagConstraints);

        getContentPane().add(panelDados);

        mnuArquivo.setText("Arquivo");

        mnuItemNovaVenda.setText("Nova Venda");
        mnuItemNovaVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemNovaVendaActionPerformed(evt);
            }
        });
        mnuArquivo.add(mnuItemNovaVenda);

        mnuItemSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        mnuItemSair.setText("Sair");
        mnuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemSairActionPerformed(evt);
            }
        });
        mnuArquivo.add(mnuItemSair);

        menuBar.add(mnuArquivo);

        mnuCadastros.setText("Cadastros");

        mnuItemClientes.setText("Clientes");
        mnuItemClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemClientesActionPerformed(evt);
            }
        });
        mnuCadastros.add(mnuItemClientes);

        mnuItemProdutos.setText("Produtos");
        mnuItemProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemProdutosActionPerformed(evt);
            }
        });
        mnuCadastros.add(mnuItemProdutos);

        mnuItemFornecedores.setText("Fornecedores");
        mnuItemFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemFornecedoresActionPerformed(evt);
            }
        });
        mnuCadastros.add(mnuItemFornecedores);

        mnuItemPedidos.setText("Pedidos");
        mnuItemPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemPedidosActionPerformed(evt);
            }
        });
        mnuCadastros.add(mnuItemPedidos);

        menuBar.add(mnuCadastros);

        mnuRelatorios.setText("Relatórios");

        mnuItemRelFluxoCaixa.setText("Fluxo de Caixa");
        mnuItemRelFluxoCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemRelFluxoCaixaActionPerformed(evt);
            }
        });
        mnuRelatorios.add(mnuItemRelFluxoCaixa);

        mnuItemRelDespesas.setText("Despesas");
        mnuItemRelDespesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemRelDespesasActionPerformed(evt);
            }
        });
        mnuRelatorios.add(mnuItemRelDespesas);

        menuBar.add(mnuRelatorios);

        mnuAdmin.setText("Administrativo");

        mnuItemUsuarios.setText("Usuarios");
        mnuItemUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemUsuariosActionPerformed(evt);
            }
        });
        mnuAdmin.add(mnuItemUsuarios);

        mnuItemGraficos.setText("Gráficos");
        mnuItemGraficos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemGraficosActionPerformed(evt);
            }
        });
        mnuAdmin.add(mnuItemGraficos);

        mnuItemDespesas.setText("Despesas");
        mnuItemDespesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemDespesasActionPerformed(evt);
            }
        });
        mnuAdmin.add(mnuItemDespesas);

        mnuItemCaixa.setText("Caixa");
        mnuItemCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemCaixaActionPerformed(evt);
            }
        });
        mnuAdmin.add(mnuItemCaixa);

        mnuItemVendas.setText("Vendas");
        mnuItemVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemVendasActionPerformed(evt);
            }
        });
        mnuAdmin.add(mnuItemVendas);

        mnuItemNotas.setText("Notas");
        mnuItemNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemNotasActionPerformed(evt);
            }
        });
        mnuAdmin.add(mnuItemNotas);

        menuBar.add(mnuAdmin);

        mnuAjuda.setText("Ajuda");

        mnuItemSobre.setText("Sobre");
        mnuItemSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemSobreActionPerformed(evt);
            }
        });
        mnuAjuda.add(mnuItemSobre);

        menuBar.add(mnuAjuda);

        setJMenuBar(menuBar);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-1070)/2, (screenSize.height-528)/2, 1070, 528);
    }// </editor-fold>//GEN-END:initComponents

    private void mnuItemNovaVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemNovaVendaActionPerformed
        executarCadastrarVenda();
    }//GEN-LAST:event_mnuItemNovaVendaActionPerformed

    private void mnuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemSairActionPerformed
        sair();        // TODO add your handling code here:
    }//GEN-LAST:event_mnuItemSairActionPerformed

    private void mnuItemClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemClientesActionPerformed
        try {
            chamarCliente();
        } catch (ParseException ex) {
            Logger.getLogger(PrincipalView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mnuItemClientesActionPerformed

    private void mnuItemProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemProdutosActionPerformed
        executarGestaoProduto();
    }//GEN-LAST:event_mnuItemProdutosActionPerformed

    private void mnuItemFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemFornecedoresActionPerformed
        try {
            chamarFornecedor();
        } catch (ParseException ex) {
            Logger.getLogger(PrincipalView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mnuItemFornecedoresActionPerformed

    private void mnuItemPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemPedidosActionPerformed
        executarGestaoPedido();
    }//GEN-LAST:event_mnuItemPedidosActionPerformed

    private void mnuItemUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemUsuariosActionPerformed
        chamarUsuario();
    }//GEN-LAST:event_mnuItemUsuariosActionPerformed

    private void mnuItemRelFluxoCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemRelFluxoCaixaActionPerformed
        chamarRelatorioFluxo();
    }//GEN-LAST:event_mnuItemRelFluxoCaixaActionPerformed

    private void mnuItemRelDespesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemRelDespesasActionPerformed
        executarRelatorioDespesas();
    }//GEN-LAST:event_mnuItemRelDespesasActionPerformed

    private void mnuItemGraficosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemGraficosActionPerformed
        executarTelaGrafico();
    }//GEN-LAST:event_mnuItemGraficosActionPerformed

    private void mnuItemDespesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemDespesasActionPerformed
        try {
            chamarDespesa();
        } catch (ParseException ex) {
            Logger.getLogger(PrincipalView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mnuItemDespesasActionPerformed

    private void mnuItemCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemCaixaActionPerformed
//        try {
//            chamarCaixa();
//        } catch (ParseException ex) {
//            Logger.getLogger(PrincipalView.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_mnuItemCaixaActionPerformed

    private void mnuItemVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemVendasActionPerformed
        executarGestaoVenda();
    }//GEN-LAST:event_mnuItemVendasActionPerformed

    private void mnuItemNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemNotasActionPerformed
        executarGestaoNotaFiscal();
    }//GEN-LAST:event_mnuItemNotasActionPerformed

    private void mnuItemSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemSobreActionPerformed
        executarSobre();
    }//GEN-LAST:event_mnuItemSobreActionPerformed

    private void btnNovaVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovaVendaActionPerformed
        executarCadastrarVenda();
    }//GEN-LAST:event_btnNovaVendaActionPerformed

    private void btnNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNotasActionPerformed
        executarGestaoNotaFiscal();
    }//GEN-LAST:event_btnNotasActionPerformed

    private void btnRelatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatoriosActionPerformed
        try {
            chamarRelatorio();
        } catch (ParseException ex) {
            Logger.getLogger(PrincipalView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRelatoriosActionPerformed

    private void btnContasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContasActionPerformed
        try {
            chamarDespesa();
        } catch (ParseException ex) {
            Logger.getLogger(PrincipalView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnContasActionPerformed

    private void btnGraficosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraficosActionPerformed
        executarTelaGrafico();
    }//GEN-LAST:event_btnGraficosActionPerformed

    private void btnPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPedidoActionPerformed
        executarGestaoPedido();
    }//GEN-LAST:event_btnPedidoActionPerformed

    private void btnFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFornecedorActionPerformed
        try {
            chamarFornecedor();
        } catch (ParseException ex) {
            Logger.getLogger(PrincipalView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnFornecedorActionPerformed

    private void btnVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVendasActionPerformed
        executarGestaoVenda();
    }//GEN-LAST:event_btnVendasActionPerformed

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
        chamarUsuario();
    }//GEN-LAST:event_btnUsuariosActionPerformed

    private void btnProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdutosActionPerformed
        executarGestaoProduto();
    }//GEN-LAST:event_btnProdutosActionPerformed

    private void btnCLientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCLientesActionPerformed
        try {
            chamarCliente();
        } catch (ParseException ex) {
            Logger.getLogger(PrincipalView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCLientesActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        sair();        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    public void setUsuarioLogado(String text) {
        this.lblUsuarioLogado.setText(text);
    }

    public void executarTelaGrafico() {
        GestaoGrafico gg = new GestaoGrafico();
        gg.setVisible(true);
        this.dispose();
    }

    public void executarGestaoNotaFiscal() {
        GestaoNotaFiscal gnf = new GestaoNotaFiscal();
        gnf.setVisible(true);
        this.dispose();
    }

    public void chamarDespesa() throws ParseException {
        GestaoDespesa gd = new GestaoDespesa();
        gd.setVisible(true);
        this.dispose();
    }

    public void chamarRelatorio() throws ParseException {
        GestaoRelatorio gr = new GestaoRelatorio();
        gr.setVisible(true);
        this.dispose();
    }

    public void executarCadastrarVenda() {
        PesquisarCliente pc = new PesquisarCliente();
        pc.setVisible(true);
        this.dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new PrincipalView().setVisible(true);
            }
        });
    }

    public void chamarCliente() throws ParseException {
        GestaoCliente c = new GestaoCliente();
        c.setVisible(true);
        this.dispose();
    }

    private void executarGestaoVenda() {
        GestaoVenda gv = new GestaoVenda();
        gv.setVisible(true);
        this.dispose();
    }

    private void executarGestaoProduto() {
        //TODO avaliar se esta abordagem é a melhor para a instância do controller
        new ProdutoController().init();
        this.dispose();
    }

    public void chamarFornecedor() throws ParseException {
        GestaoFornecedor gf = new GestaoFornecedor();
        gf.setVisible(true);
        this.dispose();
    }

    public void chamarUsuario() {
        GestaoUsuario u = null;
        try {
            u = new GestaoUsuario();
        } catch (ParseException ex) {
            Logger.getLogger(PrincipalView.class.getName()).log(Level.SEVERE, null, ex);
        }

        u.setVisible(true);
        this.dispose();
    }

    private void executarGestaoPedido() {
        GestaoPedido gp = new GestaoPedido();
        gp.setVisible(true);
        this.dispose();
    }

    private void sair() {
        if (JOptionPane.showConfirmDialog(this, "Tem certeza que deseja sair do sistema? (Pressione ESC para Cancelar)", "Confirmação", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION) {
            System.exit(1);
        }
    }

    private void chamarRelatorioFluxo() {
        EmitirRelatorioVendas rf = new EmitirRelatorioVendas();
        rf.setVisible(true);
        this.dispose();
    }

    private void executarRelatorioDespesas() {
        EmitirRelatorioEstoque rd = new EmitirRelatorioEstoque();
        rd.setVisible(true);
        this.dispose();
    }

    private void executarSobre() {
        Sobre s = new Sobre();
        s.setVisible(true);
        this.dispose();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCLientes;
    private javax.swing.JButton btnContas;
    private javax.swing.JButton btnFornecedor;
    private javax.swing.JButton btnGraficos;
    private javax.swing.JButton btnNotas;
    private javax.swing.JButton btnNovaVenda;
    private javax.swing.JButton btnPedido;
    private javax.swing.JButton btnProdutos;
    private javax.swing.JButton btnRelatorios;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JButton btnVendas;
    private javax.swing.JLabel lblClientes;
    private javax.swing.JLabel lblCompras;
    private javax.swing.JLabel lblContas;
    private javax.swing.JLabel lblFornecedor;
    private javax.swing.JLabel lblGraficos;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JLabel lblNotas;
    private javax.swing.JLabel lblNovaVenda;
    private javax.swing.JLabel lblProdutos;
    private javax.swing.JLabel lblRelatorios;
    private javax.swing.JLabel lblUsuarioLogado;
    private javax.swing.JLabel lblUsuarios;
    private javax.swing.JLabel lblVendas;
    private javax.swing.JLabel lvlLogo;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu mnuAdmin;
    private javax.swing.JMenu mnuAjuda;
    private javax.swing.JMenu mnuArquivo;
    private javax.swing.JMenu mnuCadastros;
    private javax.swing.JMenuItem mnuItemCaixa;
    private javax.swing.JMenuItem mnuItemClientes;
    private javax.swing.JMenuItem mnuItemDespesas;
    private javax.swing.JMenuItem mnuItemFornecedores;
    private javax.swing.JMenuItem mnuItemGraficos;
    private javax.swing.JMenuItem mnuItemNotas;
    private javax.swing.JMenuItem mnuItemNovaVenda;
    private javax.swing.JMenuItem mnuItemPedidos;
    private javax.swing.JMenuItem mnuItemProdutos;
    private javax.swing.JMenuItem mnuItemRelDespesas;
    private javax.swing.JMenuItem mnuItemRelFluxoCaixa;
    private javax.swing.JMenuItem mnuItemSair;
    private javax.swing.JMenuItem mnuItemSobre;
    private javax.swing.JMenuItem mnuItemUsuarios;
    private javax.swing.JMenuItem mnuItemVendas;
    private javax.swing.JMenu mnuRelatorios;
    private javax.swing.JPanel panelBotoes;
    private javax.swing.JPanel panelBotoesRelatorios;
    private javax.swing.JPanel panelDados;
    // End of variables declaration//GEN-END:variables

    class PressEnter implements KeyListener {

        @Override
        public void keyPressed(KeyEvent e) {
            // TODO Auto-generated method stub  

            if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                if (btnCLientes.isFocusOwner()) {
                    try {
                        chamarCliente();
                    } catch (ParseException ex) {
                        Logger.getLogger(PrincipalView.class.getName()).log(Level.SEVERE, null, ex);
                    }

                } else if (btnProdutos.isFocusOwner()) {
                    executarGestaoProduto();

                } else if (btnUsuarios.isFocusOwner()) {
                    chamarUsuario();

                } else if (btnFornecedor.isFocusOwner()) {
                    try {
                        chamarFornecedor();
                    } catch (ParseException ex) {
                        Logger.getLogger(PrincipalView.class.getName()).log(Level.SEVERE, null, ex);
                    }

                } else if (btnVendas.isFocusOwner()) {
                    executarGestaoVenda();
                } else if (btnContas.isFocusOwner()) {
                    try {
                        chamarDespesa();
                    } catch (ParseException ex) {
                        Logger.getLogger(PrincipalView.class.getName()).log(Level.SEVERE, null, ex);
                    }

                } else if (btnPedido.isFocusOwner()) {
                    executarGestaoPedido();
                } else if (btnNotas.isFocusOwner()) {
                    executarGestaoNotaFiscal();
                } else if (btnRelatorios.isFocusOwner()) {
                    try {
                        chamarRelatorio();
                    } catch (ParseException ex) {
                        Logger.getLogger(PrincipalView.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } else if (btnGraficos.isFocusOwner()) {
                    executarTelaGrafico();
                }
            } else if (e.getKeyCode() == KeyEvent.VK_F2) {
                executarCadastrarVenda();

            } else if (e.getKeyCode() == KeyEvent.VK_ESCAPE) {
                sair();
            }
        }

        @Override
        public void keyReleased(KeyEvent e) {
        }

        @Override
        public void keyTyped(KeyEvent e) {
        }
    }
}
