/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.cirurgica.view.notafiscal;

import br.com.cirurgica.dao.CirurgicaConnectionManager;
import br.com.cirurgica.view.PrincipalView;
import br.com.cirurgica.view.fornecedor.GestaoFornecedor;
import com.utilidades.Utilidades;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Leo
 */
public class AlterarNotaFiscal extends javax.swing.JFrame {

    Map<String, Integer> mapaTipoNotaFiscal;

    /**
     * Creates new form AlterarNotaFiscal
     */
    public AlterarNotaFiscal() {
        initComponents();

        popularComboTipoNotaFiscal();

        btnAlterar.addKeyListener(new PressEnter());
        btnCancelar.addKeyListener(new PressEnter());
        btnLimpar.addKeyListener(new PressEnter());
        txtNotaFiscal.addKeyListener(new PressEnter());
        cbTipoNotaFiscal.addKeyListener(new PressEnter());

        recuperarNotaFiscal();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnAlterar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtNotaFiscal = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cbTipoNotaFiscal = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ana Maria Cirurgica - Visualizar/Alterar Nota Fiscal");
        setBounds(new java.awt.Rectangle(300, 100, 0, 0));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        jLabel9.setText("Alteração de Nota Fiscal");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel4.setText("Tipo Nota Fiscal:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, -1, -1));

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/bt_novo_cliente.png"))); // NOI18N
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 100, 70));

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/bt_voltar.png"))); // NOI18N
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 100, 70));

        btnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/bt_clear.png"))); // NOI18N
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 100, 70));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNotaFiscal.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        txtNotaFiscal.setPreferredSize(new java.awt.Dimension(6, 24));
        txtNotaFiscal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNotaFiscalActionPerformed(evt);
            }
        });
        jPanel2.add(txtNotaFiscal, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 190, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel7.setText("N° Nota FIscal");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 300, 80));

        cbTipoNotaFiscal.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jPanel1.add(cbTipoNotaFiscal, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 280, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel1.setText("CANCELAR ALTERAÇAO");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 320, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel2.setText("ALTERAR NOTA");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, 10));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel3.setText("LIMPAR CAMPOS");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-559)/2, (screenSize.height-384)/2, 559, 384);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        alterarNotaFiscal();
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        voltar();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        limparCampos();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void txtNotaFiscalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNotaFiscalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNotaFiscalActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
voltar();
    }//GEN-LAST:event_formWindowClosing
    public void popularComboTipoNotaFiscal() {
        String sql = "select * from tiponotafiscal";
        Connection con;
        con = CirurgicaConnectionManager.getConnection();


        mapaTipoNotaFiscal = new HashMap<>();

        try {
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            while (rs.next()) {

                mapaTipoNotaFiscal.put(rs.getString("nm_tipo_nota_fiscal"), rs.getInt("cd_tipo_nota_fiscal"));
                cbTipoNotaFiscal.addItem(rs.getString("nm_tipo_nota_fiscal"));
            }

            stmt.close();

        } catch (SQLException ex) {
            Logger.getLogger(PrincipalView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void alterarNotaFiscal() {

         if (txtNotaFiscal.getText().equals("") || cbTipoNotaFiscal.getSelectedItem().equals(null)
                ){

           JOptionPane.showMessageDialog(this, "Preencha todos os campos antes de alterar uma Nota Fiscal!");

        }else{

        String sql = "update notafiscal set numero_nota_fiscal = ?, cd_tipo_nota_fiscal = ? "
                + "where numero_nota_fiscal = '" + GestaoNotaFiscal.NumNotaAlteracao + "'";

        Connection con = CirurgicaConnectionManager.getConnection();
        PreparedStatement stm;

        try {

            stm = con.prepareStatement(sql);

            stm.setString(1, txtNotaFiscal.getText());
            stm.setString(2, mapaTipoNotaFiscal.get(cbTipoNotaFiscal.getSelectedItem().toString()).toString());

            stm.executeUpdate();


            JOptionPane.showMessageDialog(this, "CADASTRO ALTERADO COM SUCESSO!!!", "Alteração", 1);


            this.setVisible(false);
            GestaoNotaFiscal gnf = new GestaoNotaFiscal();
            gnf.setVisible(true);

        } catch (Exception e) {

            e.printStackTrace();
        }

         }
    }

    public void recuperarNotaFiscal() {

        String sql = "select * from notafiscal nf join tiponotafiscal tnf on(nf.cd_tipo_nota_fiscal = tnf.cd_tipo_nota_fiscal)  where nf.numero_nota_fiscal = '" + GestaoNotaFiscal.NumNotaAlteracao + "'";
        Connection con;
        con = CirurgicaConnectionManager.getConnection();

        try {
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            if (rs.next()) {

                txtNotaFiscal.setText(rs.getString("numero_nota_fiscal"));

                cbTipoNotaFiscal.setSelectedItem(rs.getString("nm_tipo_nota_fiscal"));


            }


            stmt.close();




        } catch (SQLException ex) {
            Logger.getLogger(PrincipalView.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlterarNotaFiscal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlterarNotaFiscal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlterarNotaFiscal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlterarNotaFiscal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlterarNotaFiscal().setVisible(true);
            }
        });
    }

    public void voltar() {



        GestaoNotaFiscal gnf = new GestaoNotaFiscal();
        gnf.setVisible(true);
this.dispose();



    }

    public void limparCampos() {

        txtNotaFiscal.setText(null);
        cbTipoNotaFiscal.setSelectedIndex(0);

    }

    class PressEnter implements KeyListener {

        public void keyPressed(KeyEvent e) {
            // TODO Auto-generated method stub

            if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                if (btnAlterar.isFocusOwner()) {
                    alterarNotaFiscal();
                } else if (btnCancelar.isFocusOwner()) {
                    voltar();
                } else if (btnLimpar.isFocusOwner()) {
                    limparCampos();
                }
            } else if (e.getKeyCode() == KeyEvent.VK_ESCAPE) {
                voltar();
            }


        }

        public void keyReleased(KeyEvent e) {
        }

        public void keyTyped(KeyEvent e) {
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JComboBox cbTipoNotaFiscal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtNotaFiscal;
    // End of variables declaration//GEN-END:variables
}
