/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.cirurgica.view.usuario;

import br.com.cirurgica.view.cliente.GestaoCliente;
import br.com.cirurgica.dao.CirurgicaConnectionManager;
import br.com.cirurgica.dao.LoginDAO;
import br.com.cirurgica.model.Usuario;
import br.com.cirurgica.view.PrincipalView;
import com.utilidades.Utilidades;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Collection;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 13b Pessoal
 */
public class GestaoUsuario extends javax.swing.JFrame {

    /**
     * Creates new form GestaoUsuario
     */
    static String RGAlteracao;

    public GestaoUsuario() throws ParseException {

        initComponents();

        popularTabela();

        btnAdicioanr.addKeyListener(new PressEnter());
        btnPesquisar.addKeyListener(new PressEnter());
        btnVoltar.addKeyListener(new PressEnter());
        btnAlterar.addKeyListener(new PressEnter());
        btnExcluir.addKeyListener(new PressEnter());
        txtPesquisa.addKeyListener(new PressEnter());
    }

    private void popularTabela() {
        listaUsuarios.clear();
        Collection listaRetorno = new LoginDAO().findAll();
        if (listaRetorno != null && listaRetorno.size() > 0) {
            this.listaUsuarios.addAll(listaRetorno);
        }
    }
    /*
     public void popularTabela() throws ParseException {


     String sql = "select *, max(v.data_venda) as ultima_venda from usuario u join pessoa p on(u.cd_pessoa = p.cd_pessoa) left join venda v on(u.cd_usuario = v.cd_usuario) group by p.cd_pessoa";
     Connection con;
     con = CirurgicaConnectionManager.getConnection();


     DefaultTableModel dataModel = (DefaultTableModel) tbGestaoUsuario.getModel();

     dataModel.setNumRows(0);


     try {
     Statement stmt = con.createStatement();
     ResultSet rs = stmt.executeQuery(sql);
     while (rs.next()) {

     Object[] linha = {rs.getString("nm_pessoa"), rs.getString("tipo_usuario"), rs.getString("RG"), Utilidades.retornarDataFormatada(rs.getString("ultima_venda"))};
     dataModel.addRow(linha);
     }

     stmt.close();

     } catch (SQLException ex) {
     Logger.getLogger(PrincipalView.class.getName()).log(Level.SEVERE, null, ex);
     }
     }
     */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        listaUsuarios = org.jdesktop.observablecollections.ObservableCollections.observableList(new ArrayList());
        usuarioBean = new br.com.cirurgica.model.Usuario();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbGestaoUsuario = new javax.swing.JTable();
        tbGestaoUsuario.getSelectionModel().addListSelectionListener(new ListSelectionListener(){

            @Override
            public void valueChanged(ListSelectionEvent arg0) {
                if(tbGestaoUsuario.getSelectedRow() != -1){
                    usuarioBean = listaUsuarios.get(tbGestaoUsuario.getSelectedRow());
                    btnExcluir.setEnabled(true);
                    btnAlterar.setEnabled(true);
                }else{
                    usuarioBean = null;
                    btnExcluir.setEnabled(false);
                    btnAlterar.setEnabled(false);
                }
            }
        });
        jPanel1 = new javax.swing.JPanel();
        btnAdicioanr = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnPesquisar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtPesquisa = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnAlterar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnExcluir = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Ana Maria Cirurgica - Usuários");
        setBounds(new java.awt.Rectangle(300, 100, 0, 0));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        jLabel1.setText("Gestão de Usuários");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 188, 0, 0);
        jPanel2.add(jLabel1, gridBagConstraints);

        tbGestaoUsuario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tbGestaoUsuario.setFocusable(false);
        tbGestaoUsuario.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, listaUsuarios, tbGestaoUsuario);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${cdPessoa.nmPessoa}"));
        columnBinding.setColumnName("Nome");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${login.nmLogin}"));
        columnBinding.setColumnName("Usuário");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${tipoUsuario}"));
        columnBinding.setColumnName("Tipo Usuário");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, usuarioBean, org.jdesktop.beansbinding.ObjectProperty.create(), tbGestaoUsuario, org.jdesktop.beansbinding.BeanProperty.create("selectedElement"), "usuarioBinding");
        bindingGroup.addBinding(binding);

        tbGestaoUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbGestaoUsuarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbGestaoUsuario);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 527;
        gridBagConstraints.ipady = 113;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(8, 28, 0, 56);
        jPanel2.add(jScrollPane1, gridBagConstraints);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnAdicioanr.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAdicioanr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/bt_novo_cliente.png"))); // NOI18N
        btnAdicioanr.setPreferredSize(new java.awt.Dimension(90, 60));
        btnAdicioanr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicioanrActionPerformed(evt);
            }
        });
        btnAdicioanr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnAdicioanrKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ADICIONAR");

        btnPesquisar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/bt_pesquisar.png"))); // NOI18N
        btnPesquisar.setPreferredSize(new java.awt.Dimension(90, 60));
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("PESQUISAR");

        btnVoltar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/bt_voltar.png"))); // NOI18N
        btnVoltar.setPreferredSize(new java.awt.Dimension(90, 60));
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel4.setText("VOLTAR(ESC)");

        txtPesquisa.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel5.setText("Nome de Usuário:");

        btnAlterar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/bt_alterar.png"))); // NOI18N
        btnAlterar.setEnabled(false);
        btnAlterar.setPreferredSize(new java.awt.Dimension(90, 60));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${not empty usuarioBean}"), btnAlterar, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("ALTERAR");

        btnExcluir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/bt_excluir.png"))); // NOI18N
        btnExcluir.setEnabled(false);
        btnExcluir.setPreferredSize(new java.awt.Dimension(90, 60));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${not empty usuarioBean}"), btnExcluir, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("EXCLUIR");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(btnAdicioanr, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVoltar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(139, 139, 139))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnVoltar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAdicioanr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = -129;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 28, 27, 56);
        jPanel2.add(jPanel1, gridBagConstraints);

        getContentPane().add(jPanel2);

        bindingGroup.bind();

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-633)/2, (screenSize.height-373)/2, 633, 373);
    }// </editor-fold>//GEN-END:initComponents

    private void tbGestaoUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbGestaoUsuarioMouseClicked
    }//GEN-LAST:event_tbGestaoUsuarioMouseClicked

    private void btnAdicioanrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicioanrActionPerformed
        chamarCadastrarUsuario();
    }//GEN-LAST:event_btnAdicioanrActionPerformed

    private void btnAdicioanrKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnAdicioanrKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdicioanrKeyPressed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        pesquisarUsuario();
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        chamarVoltar();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        chamarVisualizarUsuario();
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        chamarExcluirUsuario();
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        chamarVoltar();
    }//GEN-LAST:event_formWindowClosing

    public boolean verificarUsuario(String cd_pessoa) {
        Connection con = CirurgicaConnectionManager.getConnection();
        PreparedStatement stm;

        String sql = "select *, cd_pessoa from pessoa p join where RG = '" + tbGestaoUsuario.getModel().getValueAt(tbGestaoUsuario.getSelectedRow(), 2).toString() + "'";
        String cdPessoa = "";
        try {
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            while (rs.next()) {
                cdPessoa = rs.getString("cd_pessoa");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }


        return true;
    }

    public void excluirUsuario() {

        Connection con = CirurgicaConnectionManager.getConnection();
        PreparedStatement stm;

        String sql = "select cd_pessoa from pessoa where RG = '" + tbGestaoUsuario.getModel().getValueAt(tbGestaoUsuario.getSelectedRow(), 2).toString() + "'";
        String cdPessoa = "";
        try {
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            while (rs.next()) {
                cdPessoa = rs.getString("cd_pessoa");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        int cdPessoaLogada = Utilidades.pessoaLogada.getCdPessoa().intValue();

        if (cdPessoaLogada == Integer.parseInt(cdPessoa)) {

            JOptionPane.showMessageDialog(null, "Não se pode remover um usuário logado.", "Restrição", 1);

        } else {

            sql = "delete from usuario where cd_pessoa = " + cdPessoa;

            try {
                stm = con.prepareStatement(sql);
                stm.executeUpdate();

                stm.close();
                con.close();


                JOptionPane.showMessageDialog(null, "CADASTRO EXCLUIDO COM SUCESSO!!!", "Remoção", 1);

            } catch (SQLException ex) {
                Logger.getLogger(GestaoCliente.class.getName()).log(Level.SEVERE, null, ex);
            }
        }


    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestaoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestaoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestaoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestaoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new GestaoUsuario().setVisible(true);
                } catch (ParseException ex) {
                    Logger.getLogger(GestaoUsuario.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    public void pesquisarUsuario() {
        DefaultTableModel dataModel = (DefaultTableModel) tbGestaoUsuario.getModel();

        dataModel.setNumRows(0);
        String sql = "select *, max(v.data_venda) as ultima_venda from usuario u join pessoa p on(u.cd_pessoa = p.cd_pessoa) left join venda v on(u.cd_usuario = v.cd_usuario) where p.nm_pessoa like '" + txtPesquisa.getText() + "%' group by p.cd_pessoa";

        Connection con;
        con = CirurgicaConnectionManager.getConnection();


        try {
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            while (rs.next()) {

                Object[] linha = {rs.getString("nm_pessoa"), rs.getString("tipo_usuario"), rs.getString("RG"), Utilidades.retornarDataFormatada(rs.getString("ultima_venda"))};

                dataModel.addRow(linha);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }


    }

    class PressEnter implements KeyListener {

        public void keyPressed(KeyEvent e) {
            // TODO Auto-generated method stub

            if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                if (btnAdicioanr.isFocusOwner()) {
                    chamarCadastrarUsuario();
                } else if (btnPesquisar.isFocusOwner()) {
                } else if (btnVoltar.isFocusOwner()) {
                    chamarVoltar();
                } else if (btnAlterar.isFocusOwner()) {
                    chamarVisualizarUsuario();
                } else if (btnExcluir.isFocusOwner()) {
                    chamarExcluirUsuario();
                } else if (txtPesquisa.isFocusOwner()) {
                    pesquisarUsuario();
                }
            } else if (e.getKeyCode() == KeyEvent.VK_ESCAPE) {
                chamarVoltar();
            }
        }

        @Override
        public void keyReleased(KeyEvent e) {
        }

        @Override
        public void keyTyped(KeyEvent e) {
        }
    }

    public void chamarCadastrarUsuario() {
        CadastrarUsuario cu = new CadastrarUsuario();
        cu.setVisible(true);
        this.dispose();
    }

    public void chamarVisualizarUsuario() {
        if (tbGestaoUsuario.getSelectedRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Selecione um Usuário para Visualizar e/ou Alterar seus dados.", "Seleção Necessária", 1);
        } else {

            RGAlteracao = tbGestaoUsuario.getModel().getValueAt(tbGestaoUsuario.getSelectedRow(), 2).toString();

            AlterarUsuario au = new AlterarUsuario();
            au.setVisible(true);

            this.setVisible(false);

        }

    }

    public void chamarExcluirUsuario() {
        if (tbGestaoUsuario.getSelectedRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Selecione um Usuário para poder excluir.", "Seleção Necessária", 1);
        } else {
            if (JOptionPane.showConfirmDialog(this, "Tem certeza que deseja excluir este cadastro?", "Confirmação", 2, 3) == 0) {
                excluirUsuario();
            }
        }
        popularTabela();
    }

    public void chamarVoltar() {
        PrincipalView p = new PrincipalView();
        p.setVisible(true);
        p.setUsuarioLogado(Utilidades.retornaNomeLogado());
        this.dispose();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicioanr;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private java.util.List<Usuario> listaUsuarios;
    private javax.swing.JTable tbGestaoUsuario;
    private javax.swing.JTextField txtPesquisa;
    private br.com.cirurgica.model.Usuario usuarioBean;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
