/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.cirurgica.view.venda;

import br.com.cirurgica.controller.ProdutoController;
import br.com.cirurgica.dao.MyEntityManager;
import br.com.cirurgica.dao.ProdutoDAO;
import br.com.cirurgica.dao.VendaDAO;
import br.com.cirurgica.generated.controller.ClienteJpaController;
import br.com.cirurgica.generated.controller.FormaPagamentoJpaController;
import br.com.cirurgica.generated.model.Cliente;
import br.com.cirurgica.generated.model.FormaPagamento;
import br.com.cirurgica.generated.model.VendaProduto;
import br.com.cirurgica.generated.model.VendaProdutoPK;
import br.com.cirurgica.model.Produto;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.beans.PropertyVetoException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.jdesktop.observablecollections.ObservableCollections;

/**
 *
 * @author Leo
 */
public class CadastrarVenda extends javax.swing.JFrame {

    private ProdutoDAO produtoDAO = new ProdutoDAO();
    /**
     * Creates new form CadastrarVenda
     */
    public CadastrarVenda() {
        try{
        this.listaCliente = ObservableCollections.observableList(new ArrayList<Cliente>());
        ClienteJpaController controllerCliente = new ClienteJpaController(MyEntityManager.getEntityManagerFactory());
        this.listaCliente.addAll(controllerCliente.findClienteEntities());

        this.listaFormaPagamento = ObservableCollections.observableList(new ArrayList<FormaPagamento>());
        FormaPagamentoJpaController controllerFP = new FormaPagamentoJpaController(MyEntityManager.getEntityManagerFactory());
        this.listaFormaPagamento.addAll(controllerFP.findFormaPagamentoEntities());
        }catch(Exception e){
            e.printStackTrace();
        }
        initComponents();

        this.listaTipoVenda.add("Atacado");
        this.listaTipoVenda.add("Varejo");
        
        btnAidiconar.addKeyListener(new PressEnter());
        btnCancelar.addKeyListener(new PressEnter());
        btnLimpar.addKeyListener(new PressEnter());
        btnAdicioanrCarrinho.addKeyListener(new PressEnter());
        btnRemoverCarrinho.addKeyListener(new PressEnter());
        cbFormaPagamento.addKeyListener(new PressEnter());
        txtNotaFiscal.addKeyListener(new PressEnter());
        txtValorTotal.addKeyListener(new PressEnter());
        txtTroco.addKeyListener(new PressEnter());
        txtDinheiro.addKeyListener(new PressEnter());
        cboTipoVenda.addKeyListener(new PressEnter());
        btnConfirmarTipoVenda.addKeyListener(new PressEnter());

        txtTroco.setEditable(false);
        txtValorTotal.setEditable(false);
        txtCliente.setEditable(false);
        txtValor.setEditable(false);

        //txtCliente.setText(PesquisarCliente.nmPessoa);


        panelConteudo.setVisible(false);
        this.setBounds(this.getBounds().x, 0, this.getBounds().width, this.getBounds().height);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        moneyCellRenderer = new br.com.cirurgica.view.utils.cell.MoneyCellRenderer();
        moneyCellEditor = new br.com.cirurgica.view.utils.cell.MoneyCellEditor();
        dateConverter = new br.com.cirurgica.view.utils.DateConverter();
        moneyConverter = new br.com.cirurgica.view.utils.MoneyConverter();
        moneyFormattedConverter = new br.com.cirurgica.view.utils.MoneyFormattedConverter();
        integerCellEditor = new br.com.cirurgica.view.utils.cell.IntegerCellEditor();
        vendaBean = new br.com.cirurgica.generated.model.Venda();
        listaCliente = listaCliente;
        listaFormaPagamento = listaFormaPagamento;
        listaTipoVenda = ObservableCollections.observableList(new ArrayList<String>());
        panelTitulo = new javax.swing.JPanel();
        lblTipoVenda = new javax.swing.JLabel();
        cboTipoVenda = new javax.swing.JComboBox();
        btnConfirmarTipoVenda = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        panelConteudo = new javax.swing.JPanel();
        btnAidiconar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbCarrinho = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        painelBuscarProduto = new javax.swing.JPanel();
        btnAdicioanrCarrinho = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtProduto = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btnProcurar = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        txtQuantidade = new javax.swing.JTextField();
        lblValorPago = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtValorTotal = new javax.swing.JTextField();
        txtTroco = new javax.swing.JTextField();
        txtDinheiro = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cbFormaPagamento = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        cbParcelas = new javax.swing.JComboBox();
        txtValor = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtDesconto = new javax.swing.JTextField();
        painelCliente = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNotaFiscal = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        cbDataVenda = new com.toedter.calendar.JDateChooser();
        txtCliente = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        btnRemoverCarrinho = new javax.swing.JButton();

        moneyCellRenderer.setText("moneyCellRenderer1");

        vendaBean.setCdNotaFiscal(new br.com.cirurgica.generated.model.NotaFiscal());
        try{
            vendaBean.setVendaProdutoCollection(ObservableCollections.observableList(new ArrayList<VendaProduto>()));
        }catch(PropertyVetoException ex){
            Logger.getLogger(CadastrarVenda.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this,"Erro ao associar itens à venda");
        }

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Ana Maria Cirurgica - Cadastrar Venda");
        setBounds(new java.awt.Rectangle(300, 10, 0, 0));
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/resources/icon-principal.png")));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        panelTitulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTipoVenda.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblTipoVenda.setText("Tipo da Venda:");
        panelTitulo.add(lblTipoVenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, 20));

        org.jdesktop.swingbinding.JComboBoxBinding jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, listaTipoVenda, cboTipoVenda);
        bindingGroup.addBinding(jComboBoxBinding);
        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, vendaBean, org.jdesktop.beansbinding.ELProperty.create("${nmTipoVenda}"), cboTipoVenda, org.jdesktop.beansbinding.BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        panelTitulo.add(cboTipoVenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 131, -1));

        btnConfirmarTipoVenda.setText("Confirmar");
        btnConfirmarTipoVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarTipoVendaActionPerformed(evt);
            }
        });
        panelTitulo.add(btnConfirmarTipoVenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 103, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        jLabel9.setText("Cadastrar Venda");
        panelTitulo.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(363, 6, 197, -1));

        getContentPane().add(panelTitulo);

        panelConteudo.setEnabled(false);
        panelConteudo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAidiconar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/bt_novo_cliente.png"))); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, vendaBean, org.jdesktop.beansbinding.ELProperty.create("${vlTroco >= 0}"), btnAidiconar, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        btnAidiconar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAidiconarActionPerformed(evt);
            }
        });
        panelConteudo.add(btnAidiconar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 530, 80, 60));

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/cancel.png"))); // NOI18N
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        panelConteudo.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 530, 80, 60));

        btnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/bt_clear.png"))); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tbCarrinho, org.jdesktop.beansbinding.ELProperty.create("${rowCount > 0}"), btnLimpar, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        panelConteudo.add(btnLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 530, 80, 60));

        tbCarrinho.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tbCarrinho.setFocusable(false);
        tbCarrinho.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        org.jdesktop.beansbinding.ELProperty eLProperty = org.jdesktop.beansbinding.ELProperty.create("${vendaProdutoCollection}");
        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, vendaBean, eLProperty, tbCarrinho, "vendaProdutoBinding");
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${vendaProdutoPK.cdProduto.cdFarmaceutico}"));
        columnBinding.setColumnName("Código");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${vendaProdutoPK.cdProduto.nome}"));
        columnBinding.setColumnName("Nome");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${qtdeProduto}"));
        columnBinding.setColumnName("Qtde");
        columnBinding.setColumnClass(Integer.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${vlVendaProduto}"));
        columnBinding.setColumnName("Preço");
        columnBinding.setColumnClass(Float.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${totalItem}"));
        columnBinding.setColumnName("Total Item");
        columnBinding.setColumnClass(Float.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${vendaProdutoPK.cdProduto.cor}"));
        columnBinding.setColumnName("Cor");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${vendaProdutoPK.cdProduto.tamanho}"));
        columnBinding.setColumnName("Tamanho");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane1.setViewportView(tbCarrinho);
        tbCarrinho.getColumnModel().getColumn(0).setPreferredWidth(50);
        tbCarrinho.getColumnModel().getColumn(1).setPreferredWidth(200);
        tbCarrinho.getColumnModel().getColumn(2).setPreferredWidth(20);
        tbCarrinho.getColumnModel().getColumn(2).setCellEditor(null);
        tbCarrinho.getColumnModel().getColumn(3).setPreferredWidth(50);
        tbCarrinho.getColumnModel().getColumn(3).setCellEditor(moneyCellEditor);
        tbCarrinho.getColumnModel().getColumn(3).setCellRenderer(moneyCellRenderer);
        tbCarrinho.getColumnModel().getColumn(4).setPreferredWidth(50);
        tbCarrinho.getColumnModel().getColumn(4).setCellEditor(moneyCellEditor);
        tbCarrinho.getColumnModel().getColumn(4).setCellRenderer(moneyCellRenderer);
        tbCarrinho.getColumnModel().getColumn(5).setPreferredWidth(40);
        tbCarrinho.getColumnModel().getColumn(6).setPreferredWidth(30);

        panelConteudo.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 860, 290));

        jLabel1.setText("Carrinho:");
        panelConteudo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Valor Total:");
        panelConteudo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 490, -1, 20));

        painelBuscarProduto.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        painelBuscarProduto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAdicioanrCarrinho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/bt_nova_venda.png"))); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, txtProduto, org.jdesktop.beansbinding.ELProperty.create("${not empty text}"), btnAdicioanrCarrinho, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        btnAdicioanrCarrinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicioanrCarrinhoActionPerformed(evt);
            }
        });
        painelBuscarProduto.add(btnAdicioanrCarrinho, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 70, 50));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel2.setText("Produto:");
        painelBuscarProduto.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        txtProduto.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        painelBuscarProduto.add(txtProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 170, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("ADICIONAR PRODUTO");
        painelBuscarProduto.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 120, -1));

        btnProcurar.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnProcurar.setText("Procurar");
        btnProcurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcurarActionPerformed(evt);
            }
        });
        painelBuscarProduto.add(btnProcurar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel19.setText("Quantidade:");
        painelBuscarProduto.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        txtQuantidade.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, txtProduto, org.jdesktop.beansbinding.ELProperty.create("${not empty text}"), txtQuantidade, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        painelBuscarProduto.add(txtQuantidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 61, -1));

        panelConteudo.add(painelBuscarProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 452, 85));

        lblValorPago.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblValorPago.setText("Valor Pago:");
        panelConteudo.add(lblValorPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 450, -1, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Troco:");
        panelConteudo.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 490, -1, 20));

        txtValorTotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtValorTotal.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtValorTotal.setEnabled(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, vendaBean, org.jdesktop.beansbinding.ELProperty.create("${valorTotalVenda}"), txtValorTotal, org.jdesktop.beansbinding.BeanProperty.create("text"), "valorTotalBinding");
        binding.setConverter(moneyFormattedConverter);
        bindingGroup.addBinding(binding);

        panelConteudo.add(txtValorTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 490, 160, -1));

        txtTroco.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTroco.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtTroco.setEnabled(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, vendaBean, org.jdesktop.beansbinding.ELProperty.create("${vlTroco}"), txtTroco, org.jdesktop.beansbinding.BeanProperty.create("text"), "trocoBinding");
        binding.setConverter(moneyFormattedConverter);
        bindingGroup.addBinding(binding);

        panelConteudo.add(txtTroco, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 490, 160, -1));

        txtDinheiro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDinheiro.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, vendaBean, org.jdesktop.beansbinding.ELProperty.create("${vlDinheiro}"), txtDinheiro, org.jdesktop.beansbinding.BeanProperty.create("text"), "valorPagoBinding");
        binding.setConverter(moneyFormattedConverter);
        bindingGroup.addBinding(binding);

        panelConteudo.add(txtDinheiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 450, 160, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Forma de Pagamento:");
        panelConteudo.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, -1, 20));

        cbFormaPagamento.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, listaFormaPagamento, cbFormaPagamento);
        bindingGroup.addBinding(jComboBoxBinding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, vendaBean, org.jdesktop.beansbinding.ELProperty.create("${cdFormaPagamento}"), cbFormaPagamento, org.jdesktop.beansbinding.BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        panelConteudo.add(cbFormaPagamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, 158, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("CONCLUIR VENDA");
        panelConteudo.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 600, 100, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("LIMPAR VENDA");
        panelConteudo.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 600, 100, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("CANCELAR VENDA");
        panelConteudo.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 600, 100, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Parcelas :");
        panelConteudo.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 410, -1, 20));

        cbParcelas.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbParcelas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, vendaBean, org.jdesktop.beansbinding.ELProperty.create("${nrParcelas}"), cbParcelas, org.jdesktop.beansbinding.BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        panelConteudo.add(cbParcelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 410, 41, -1));

        txtValor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtValor.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtValor.setEnabled(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, vendaBean, org.jdesktop.beansbinding.ELProperty.create("${vlParcela}"), txtValor, org.jdesktop.beansbinding.BeanProperty.create("text"), "valorParcelaBinding");
        binding.setConverter(moneyFormattedConverter);
        bindingGroup.addBinding(binding);

        panelConteudo.add(txtValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 410, 160, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Valor Parcela:");
        panelConteudo.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 410, -1, 20));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("Desconto:");
        panelConteudo.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 450, -1, 20));

        txtDesconto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, vendaBean, org.jdesktop.beansbinding.ELProperty.create("${vlDesconto}"), txtDesconto, org.jdesktop.beansbinding.BeanProperty.create("text"), "valorDescontoBinding");
        binding.setConverter(moneyFormattedConverter);
        bindingGroup.addBinding(binding);

        panelConteudo.add(txtDesconto, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 450, 160, -1));

        painelCliente.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        painelCliente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel7.setText("Cliente:");
        painelCliente.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 8, 80, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel4.setText("N° Nota Fiscal:");
        painelCliente.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 35, 80, 20));

        txtNotaFiscal.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, vendaBean, org.jdesktop.beansbinding.ELProperty.create("${cdNotaFiscal.numeroNotaFiscal}"), txtNotaFiscal, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        painelCliente.add(txtNotaFiscal, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 35, 130, 22));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel17.setText("Data da Venda:");
        painelCliente.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 80, 20));

        cbDataVenda.setMaxSelectableDate(new java.util.Date(4102455681000L));
        cbDataVenda.setMinSelectableDate(new java.util.Date(915159681000L));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, vendaBean, org.jdesktop.beansbinding.ELProperty.create("${dataVenda}"), cbDataVenda, org.jdesktop.beansbinding.BeanProperty.create("date"));
        bindingGroup.addBinding(binding);

        painelCliente.add(cbDataVenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 150, 22));

        jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, listaCliente, txtCliente);
        bindingGroup.addBinding(jComboBoxBinding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, vendaBean, org.jdesktop.beansbinding.ELProperty.create("${cdCliente}"), txtCliente, org.jdesktop.beansbinding.BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        painelCliente.add(txtCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 290, -1));

        panelConteudo.add(painelCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 400, 85));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        jLabel8.setText("REMOVER PRODUTO");
        panelConteudo.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 470, -1, -1));

        btnRemoverCarrinho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/bt_retirar_venda.png"))); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tbCarrinho, org.jdesktop.beansbinding.ELProperty.create("${not empty selectedElement}"), btnRemoverCarrinho, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        btnRemoverCarrinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverCarrinhoActionPerformed(evt);
            }
        });
        panelConteudo.add(btnRemoverCarrinho, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 410, 70, 50));

        getContentPane().add(panelConteudo);

        bindingGroup.bind();

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-902)/2, (screenSize.height-728)/2, 902, 728);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        voltar();
    }//GEN-LAST:event_formWindowClosing

    private void btnConfirmarTipoVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarTipoVendaActionPerformed
        confirmarTipoVenda();
    }//GEN-LAST:event_btnConfirmarTipoVendaActionPerformed

    private void btnRemoverCarrinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverCarrinhoActionPerformed
        this.removerItem();
    }//GEN-LAST:event_btnRemoverCarrinhoActionPerformed

    private void btnProcurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcurarActionPerformed
        produto = new ProdutoController().find();
        if (produto != null) {
            this.txtProduto.setText(produto.getCdFarmaceutico());
            this.txtQuantidade.setText("1");
            this.txtQuantidade.requestFocus();
        }
    }//GEN-LAST:event_btnProcurarActionPerformed

    private void btnAdicioanrCarrinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicioanrCarrinhoActionPerformed
        this.acionarAdicionar();
    }//GEN-LAST:event_btnAdicioanrCarrinhoActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        this.limparCampos();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        voltar();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAidiconarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAidiconarActionPerformed
        this.incluirVenda();
    }//GEN-LAST:event_btnAidiconarActionPerformed

    private void voltar() {
        if (JOptionPane.showConfirmDialog(this, "Tem certeza que deseja cancelar o cadastro? (Pressione ESC para Cancelar)", "Confirmação", 2, 3) == 0) {
            voltarGestaoVenda();
        }
    }

    private void limparCampos() {
        this.limparProduto();
        this.vendaBean.getVendaProdutoCollection().clear();
    }

    public void adicionarAoCarrinho() throws Exception {
        try {
            String cdProduto = txtProduto.getText();
            if (!cdProduto.trim().equals("")) {
                Produto p = produtoDAO.getByCodigoFarmaceutico(cdProduto);
                if (p != null) {
                    popularTabela(p);
                } else {
                    JOptionPane.showMessageDialog(this, "Produto não encontrado!", "Busca de produto", JOptionPane.WARNING_MESSAGE);
                    txtProduto.requestFocus();
                }
            } else {
                JOptionPane.showMessageDialog(this, "O produto não foi adicionado a compra. Favor:"
                        + "\n1- Preencher o código do produto, ou"
                        + "\n2- Buscar por um produto", "Busca de produto", JOptionPane.WARNING_MESSAGE);
                txtProduto.requestFocus();
            }
        } catch (Exception ex) {
            Logger.getLogger(CadastrarVenda.class.getName()).log(Level.SEVERE, null, ex);
            throw ex;
        }
    }

    private void removerDoCarrinho() throws SQLException {
        this.vendaBean.removeItemVenda(this.tbCarrinho.getSelectedRow());
    }

    private void popularTabela(Produto p) throws Exception {
        VendaProduto vp = new VendaProduto();

        int quantidade = 0;
        try {
            quantidade = Integer.parseInt(txtQuantidade.getText().trim());
        } catch (NumberFormatException ex) {
            txtQuantidade.requestFocus();
            throw new Exception("Quantidade inválida!", ex);
        }
        if (quantidade <=0 ) {
            throw new Exception("Quantidade deve ser igual ou maior a 1");
        }
        
        if (quantidade > p.getQtdeEstoque()) {
            throw new Exception("Estoque insuficiente! Estoque atual: " + p.getQtdeEstoque());
        }

        if (this.vendaBean.getNmTipoVenda().equals("Atacado")) {
            vp.setVlVendaProduto(p.getValorVendaAtacado());
        } else {
            vp.setVlVendaProduto(p.getValorVenda());
        }

        vp.setQtdeProduto(quantidade);

        VendaProdutoPK pk = new VendaProdutoPK();
        pk.setCdProduto(p);
        pk.setCdVenda(vendaBean);
        vp.setVendaProdutoPK(pk);

        this.vendaBean.addItemVenda(vp);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;


                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarVenda.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new CadastrarVenda().setVisible(true);
            }
        });


    }

    private void confirmarTipoVenda() {
        panelConteudo.setVisible(true);
        btnConfirmarTipoVenda.setVisible(false);
        cboTipoVenda.setEnabled(false);
        txtProduto.requestFocus();
    }

    private void acionarAdicionar() {
        try {
            adicionarAoCarrinho();
            limparProduto();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao adicionar item: \n - " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void limparProduto() {
        this.produto = null;
        this.txtProduto.setText("");
        this.txtQuantidade.setText("");
        this.txtProduto.requestFocus();
    }

    private void voltarGestaoVenda() {
        GestaoVenda gv = new GestaoVenda();
        gv.setVisible(true);
        this.dispose();
    }

    private void incluirVenda() throws HeadlessException {
        try {
            if (vendaBean.getVendaProdutoCollection().size() <= 0) {
                JOptionPane.showMessageDialog(this, "Favor adicionar itens a venda", "Alerta!", JOptionPane.INFORMATION_MESSAGE);
            }
            VendaDAO dao = new VendaDAO();
            dao.incluir(vendaBean);
            JOptionPane.showMessageDialog(this, "Venda incluída com sucesso!", "Sucesso!", JOptionPane.INFORMATION_MESSAGE);
            voltarGestaoVenda();
        } catch (Exception ex) {
            Logger.getLogger(CadastrarVenda.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Erro ao incluir a venda");
        }
    }

    private void removerItem() throws HeadlessException {
        if (tbCarrinho.getSelectedRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Selecione um Produto para poder remover do carrinho.", "Seleção Necessária", 1);
        } else {
            try {
                if (JOptionPane.showConfirmDialog(this, "Deseja excluir o item selecionado?", "Exclusão do item", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                    removerDoCarrinho();
                }
                //gerarTroco(txtDinheiro.getText());
            } catch (SQLException ex) {
                Logger.getLogger(CadastrarVenda.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    class PressEnter implements KeyListener {

        @Override
        public void keyPressed(KeyEvent e) {
            // TODO Auto-generated method stub  

            if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                if (btnAidiconar.isFocusOwner()) {
                    incluirVenda();
                } else if (cboTipoVenda.isFocusOwner() || btnConfirmarTipoVenda.isFocusOwner()) {
                    confirmarTipoVenda();
                } else if (btnCancelar.isFocusOwner()) {
                    voltar();
                } else if (btnLimpar.isFocusOwner()) {
                    limparCampos();
                } else if (btnAdicioanrCarrinho.isFocusOwner()) {
                    acionarAdicionar();
                } else if (btnRemoverCarrinho.isFocusOwner()) {
                    removerItem();
                }
            } else if (e.getKeyCode() == KeyEvent.VK_ESCAPE) {
                voltar();
            }


        }

        @Override
        public void keyReleased(KeyEvent e) {
        }

        @Override
        public void keyTyped(KeyEvent e) {
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicioanrCarrinho;
    private javax.swing.JButton btnAidiconar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConfirmarTipoVenda;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnProcurar;
    private javax.swing.JButton btnRemoverCarrinho;
    private com.toedter.calendar.JDateChooser cbDataVenda;
    private javax.swing.JComboBox cbFormaPagamento;
    private javax.swing.JComboBox cbParcelas;
    private javax.swing.JComboBox cboTipoVenda;
    private br.com.cirurgica.view.utils.DateConverter dateConverter;
    private br.com.cirurgica.view.utils.cell.IntegerCellEditor integerCellEditor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTipoVenda;
    private javax.swing.JLabel lblValorPago;
    private java.util.List<Cliente> listaCliente;
    private java.util.List<FormaPagamento> listaFormaPagamento;
    private java.util.List<String> listaTipoVenda;
    private br.com.cirurgica.view.utils.cell.MoneyCellEditor moneyCellEditor;
    private br.com.cirurgica.view.utils.cell.MoneyCellRenderer moneyCellRenderer;
    private br.com.cirurgica.view.utils.MoneyConverter moneyConverter;
    private br.com.cirurgica.view.utils.MoneyFormattedConverter moneyFormattedConverter;
    private javax.swing.JPanel painelBuscarProduto;
    private javax.swing.JPanel painelCliente;
    private javax.swing.JPanel panelConteudo;
    private javax.swing.JPanel panelTitulo;
    private javax.swing.JTable tbCarrinho;
    private javax.swing.JComboBox txtCliente;
    private javax.swing.JTextField txtDesconto;
    private javax.swing.JTextField txtDinheiro;
    private javax.swing.JTextField txtNotaFiscal;
    private javax.swing.JTextField txtProduto;
    private javax.swing.JTextField txtQuantidade;
    private javax.swing.JTextField txtTroco;
    private javax.swing.JTextField txtValor;
    private javax.swing.JTextField txtValorTotal;
    private br.com.cirurgica.generated.model.Venda vendaBean;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
    private br.com.cirurgica.model.Produto produto;
}
